### ISSUE TITLE
Function to calculate hold

### ISSUE THREAD

**Issue by pnxenopoulos** [pnxenopoulos/implied#6]
How much the book "keeps". For example, -102/+102 is 0 hold. -110/-110 is 4.55% hold

so, we calculate probabilities, sum them up and subtract 1

**Comment by ofrighil** [comment]
I think we should specify how exactly we should write this. For example, should this hold just be a standalone function that takes in two probabilities and returns the hold? Or should there be a method on each object that does this?

**Comment by pnxenopoulos** [comment]
Hold needs a collection of odds, so I think it would look like the deviggers
